redhat-appstudio/o11y

.tekton/pull-request.yaml
automation/test.sh

Add a pipeline that will be triggered for PRs.

Add CI using Tekton

---

automation/test.sh
test/promql/example.yaml
test/promql/example2.yaml

Install promtool to allow promql unit testing and provide example test cases.

test(STONEO11Y-43): add promql unit testing

---

.gitlint
.tekton/pull-request.yaml

add gitlint configs and introduce a tekton task to run it.
This will validate the commits in the PR against the rules defined
on the gitlint file.

test(STONEO11Y-48): add gitlint

---

.tekton/pull-request.yaml
.yamllint

add .yamllint config and yaml-lint to CI.

test(STONEO11Y-49): add yamllint

---

.tekton/pull-request.yaml
automation/pint_lint.sh

Pint[1] is a Prometheus rule linter.
[1] https://github.com/cloudflare/pint

chore(STONEO11Y-52): Setup pint for the CI

---

OWNERS

Add owners file which should hopefully address issues causing the ci not to run in some cases.

chore: add owners file

---

CONTRIBUTING.md

Add a file to guide developers with setting up their dev environments and explains CI procedures and code review guidelines.

chore(STONEO11Y-53): add contributing guide

---

README.md

- Create a README file
- Add limitations for `appstudio_container_network_transmit_bytes_total` and init_containers

chore(STONEO11Y-75): Add limitations to README

---

prometheus/base/alerting/prometheus.pod_alerts.yaml
test/promql/tests/test_crashloopbackoff.yaml

Create an alerting rule for CrashLoopBackOff pods and write related unit tests.

chore(STONEO11Y-100): Alerting rule for crash looping pods

---

prometheus/base/alerting/kustomization.yaml
prometheus/base/alerting/prometheus.quota_alerts.yaml
test/promql/tests/test_quota_exceeded.yaml

Create an alerting rule for Quota Exceeded error and add related unit test cases.

chore(STONEO11Y-101): Alerting rule for Quota Exceeded

---

prometheus/base/alerting/kustomization.yaml
prometheus/base/alerting/prometheus.pv_alerts.yaml
test/promql/tests/test_persistentvolumeissues.yaml

- Created a new alerting rule for persistent volume issues.
- Added related unit test cases.

chore(STONEO11Y-102): Alerting rule for persistent volume issues

---

prometheus/base/alerting/kustomization.yaml
prometheus/base/alerting/prometheus.argocd_alerts.yaml
test/promql/tests/test_degraded_argocd.yaml

* Create an alerting rule for argoCD apps with 'Degraded' health status in the past 5 minutes.

chore(STONEO11Y-97): Alert rule for degraded argoCD apps

---

grafana/dashboard.yaml
grafana/dashboards/o11y-dashboard.json
grafana/kustomization.yaml

Add an example grafana dashboard

Add an example grafana dashboard

---

review.md

Adds a guide with basic principles and tips for code-review to assist our team and newcomers during the review process and help make it healthy and useful.

chore(STONEO11Y-237): Code-review guide

---

prometheus/base/alerting/prometheus.controller_alerts.yaml
prometheus/base/alerting/prometheus.pod_alerts.yaml
prometheus/base/alerting/prometheus.pv_alerts.yaml
prometheus/base/alerting/prometheus.quota_alerts.yaml
test/promql/tests/test_controller_reconciliation_errors.yaml
test/promql/tests/test_crashloopbackoff.yaml
test/promql/tests/test_notready_pods.yaml
test/promql/tests/test_persistentvolumeissues.yaml
test/promql/tests/test_quota_exceeded.yaml
test/promql/tests/test_unschedulable_pods.yaml

Add source cluster information to alerting rules and description
Add source cluster details to the test cases

chore(RHTAPWATCH-297): Modify the alerting rules and test cases with source_cluster information

---

rhobs/alerting/prometheus.controller_alerts.yaml
rhobs/alerting/prometheus.pod_alerts.yaml
rhobs/alerting/prometheus.pv_alerts.yaml
rhobs/alerting/prometheus.quota_alerts.yaml

update alerting rules according to RHOBS
Signed-off-by: Kousalya Lakshmanan <klakshma@redhat.com>

fix(RHTAPWATCH-153): Prepare alerting rules for RHOBS

---

rhobs/alerting/prometheus.quota_alerts.yaml
test/promql/tests/test_quota_exceeded.yaml

Adding link to SOP to provide instructions for dealing with the alert.

chore(RHTAPWATCH-350): add sop link to alert QuotaExceeded

---

rhobs/alerting/prometheus.pod_alerts.yaml
test/promql/tests/test_notready_pods.yaml

- Add SOP URL to PodsNotReady alert rule and its test case file

chore(RHTAPWATCH-348): Add SOP URL to alert rule PodsNotReady

---

rhobs/alerting/prometheus.pv_alerts.yaml
test/promql/tests/test_persistentvolumeissues.yaml

- Add SOP URL to the PV alerting rule and its test cases

chore(RHTAPWATCH-349): Add SOP URL to alert rule PersistentVolumeIssues

---

README.md

- Add alerting rules with description
- Remove Grafana dashboard details from README.md

chore(RHTAPWATCH-360): update o11y README file

---

README.md

Update readme file after adding control plane rules to the repo

chore(RHTAPWATCH-527): Update readme file

---

config/probes/monitoring/grafana/base/grafana-datasource-probe.yaml

Update probe to select only from the latest grafana api 
Fix lint issues

chore(RHTAPWATCH-404): update probe

---

rhobs/alerting/data_plane/prometheus.controller_alerts.yaml
test/promql/tests/data_plane/controller_reconciliation_errors_test.yaml

Update the controller reconciliation alert:
- modify the time range to 10 minutes and the error rate to 10%
- Update tests

chore(RHTAPWATCH-534): tweak controller reconciliation alert

---

README.md
rhobs/alerting/data_plane/prometheus.application_alerts.yaml
test/promql/tests/data_plane/application_errors_test.yaml

- Label `slo: true` added to any existing SLO alert rules.

chore(RHTAPWATCH-525): Add slo label to SLO alert rules

---

README.md

- update links for control plane and data plane staging and prod env

fix(RHTAPWATCH-545): Update the control plane and data plane links in O11y/README

---

config/probes/monitoring/grafana/base/grafana-datasource-probe.yaml

fix(RHTAPWATCH-404): rename probe

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

See https://issues.redhat.com/browse/GITOPSRVCE-750

feat[GITOPSRVCE-750]: Add visualization for Synced Applications SLO

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Add SPI SLO visualization as per https://issues.redhat.com/browse/SVPI-645

feat(SVPI-645): Add visualizations for the 5xx service provider responses SLO

---

README.md

Update the readme file to reflect the changes in app-interface

chore(RHTAPWATCH-553): update readme file

---

README.md

Add link to documentation about adding metrics and labels missing in AppSRE Grafana.

docs(RHTAPWATCH-554): adding metrics and labels

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

JIRA LINK - https://issues.redhat.com/browse/GITOPSRVCE-753

Add visualization for Cluster Agent Operations SLO

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Issue - My recent PR got merged https://github.com/redhat-appstudio/o11y/pull/104, but there seems to be some issues that opens a different panel if I edit any of 6 panels I created. Probably it is caused by JSON changes via some other PR. Hence updating IDs for my panels which should fix this issue.

feat(GITOPSRVCE-751): Update SLO visualization

---

rhobs/alerting/data_plane/prometheus.application_alerts.yaml
test/promql/tests/data_plane/application_errors_test.yaml

Update the runbook-url in the application alert and test files

chore(DEVHAS-506): Update runbook URLs for Application alerts

---

.tekton/pull-request.yaml

- Add GO unit tests on each opened pull request.
Ticket:
[RHTAPWATCH-564](https://issues.redhat.com/browse/RHTAPWATCH-564)

chore(RHTAPWATCH-564): Run exporter service Go unit tests for each PR opened

---

rhobs/alerting/data_plane/prometheus.gitops_sync_alerts.yaml
test/promql/tests/data_plane/gitops_sync_test.yaml

See https://issues.redhat.com/browse/GITOPSRVCE-750.  Alert rule and test.

feat(GITOPSRVCE-750): Add alert rule/test for Synced Applications SLO

---

.tekton/pull-request.yaml
CONTRIBUTING.md
Makefile
Pipfile
Pipfile.lock
config/probes/monitoring/grafana/base/grafana-datasource-probe.yaml
test/promql/tests/data_plane/component_errors_test.yaml

- Add yaml lint in the makefile
- Add yaml lint to tekton 
Ticket:
[RHTAPWATCH-539](https://issues.redhat.com/browse/RHTAPWATCH-539)

chore(RHTAPWATCH-539): Run yamllint checks for each opened PR

---

rhobs/alerting/data_plane/prometheus.latency_snapshot_to_static_integration_plr_creation_alerts.yaml
test/promql/tests/data_plane/latency_snapshot_to_static_integration_plr_creation_test.yaml

Adding alerting for snaphot created to integration PLR in static evn created SLO.

feat(STONEINTG-560): alerting for IS SLO 2A

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Some minor improvements in the SPI SLO panel to align with others...

chore(SVPI-586): Align SPI SLO panel to be more inline with others

---

rhobs/alerting/data_plane/prometheus.gitops_cluster_agent_op_alerts.yaml
test/promql/tests/data_plane/gitops_cluster_agent_operation_test.yaml

JIRA - https://issues.redhat.com/browse/GITOPSRVCE-753

feat(GITOPSRVCE-753): Add alert rule/test for Cluster Agent Operation SLO

---

rhobs/alerting/data_plane/prometheus.seb_created_to_ready_alerts.yaml
test/promql/tests/data_plane/seb_created_to_ready_test.yaml

add alert rule and testing for same for SLO 6
Integration Service - Snapshot Environment Binding created to ready seconds

feat(STONEINTG-559): add alert and test for SLO 6 Intg Svc

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Intg Svc SLO 1 panel to RHTAP SLOs
Intg Svc SLO 2a panel to RHTAP SLO's
Intg Svc SLO 5 panel to RHTAP SLO's
Intg Svc SLO 6 panel to RHTAP SLO's

feat(STONEINTG-558-561) add SLO grafana panels to RHTAP dash

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

- Adds a couple of new panels for the component creation SLO metrics
- New metrics are not available yet but risk is low since it's very similar to the Application creation charts.

chore(DEVHAS-572):Add component creation charts

---

rhobs/alerting/data_plane/prometheus.gitops_deployment_alerts.yaml
test/promql/tests/data_plane/gitops_deployment_test.yaml

This PR is to add alert rules and their tests for Deployments SLOs added by GitOps Service team.
https://issues.redhat.com/browse/GITOPSRVCE-751

feat(GITOPSRVCE-751): Add alert rule/test for Deployment SLO

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Add visualization panels for OAuth completion time SLO for SPI

chore(SVPI-706): Add visualization for OAuth completion time SLO

---

rhobs/alerting/data_plane/prometheus.oauth_alerts.yaml
test/promql/tests/data_plane/oauth_time_test.yaml

Add an alert for the OAuth completion time SLO

chore(SVPI-705): Add alert for OAuth completion time SLO

---

config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml
exporters/dsexporter/dsexporter.go

- Add service monitor to scrape the metrics

chore(RHTAPWATCH-566): Write service monitor to scrape the metrics

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

This PR add Release's SLOs visualizations to Grafana SLO dashboard

chore(RHTAPREL-282): add release SLO visualizations

---

.tekton/o11y-push.yaml

Removed infra-deployments-mr task from the push
tekton pipeline.

chore: remove infra-deployments update task

---

exporters/dsexporter/dsexporter.go

Small change in dsexporter.go to trigger the
release pipeline.

chore: Small change in dsexporter.go

---

.kube-linter.yaml
config/exporters/monitoring/grafana/base/kustomization.yaml
config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml

Update the image and tag used in deployment and kustomization file since in the release pipeline image is updated.

chore(RHTAPWATCH-742): Update the image used in deployment

---

README.md

The `Updating Alerts` section in README.md contained broken links which were fixed.

fix(RHTAPWATCH-761): Fix broken links in README.md

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Remove SEB following to [STONEINTG-761  ](https://issues.redhat.com/browse/STONEINTG-761)

fix(stoneintg-761): drop SEB from grafana

---

README.md

Added recording rules documentation for deploying to app-interface
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-741

docs(RHTAPWATCH-741): Update readme

---

config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml

Updated cluster role name since it's conflicting
with other ArgoCD components resource name.

chore: Update cluster role name

---

README.md
rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
test/promql/tests/control_plane/argocd_test.yaml

Add `control_plane="true"` label to control plane alerts

chore(RHTAPWATCH-871): add control_plane label

---

dashboards/grafana-dashboard-stonesoup-argocd.configmap.yaml

This PR will add two additional Grafana Dashboard panels :-
Signed-off-by: Manish Kumar

chore(RHTAPSRE-456): Adding additional grafana panels to add uptime

---

dashboards/grafana-dashboard-stonesoup-argocd.configmap.yaml

This pull request will add  `${namespace}` for the namespace parameter. 
Signed-off-by: Manish Kumar

chore(RHTAPSRE-485): Adding New Namespaces for ArgoCD Dashboard

---

rhobs/alerting/data_plane/prometheus.smee_deployment_alerts.yaml
test/promql/tests/data_plane/mismatch_smee_deployment_replicas_test.yaml

- Create alert rule to monitor deployment replicas of smee
- Add tests to the alert

chore(RHTAPWATCH-886): smee deployment replicas alert rule

---

README.md

Add recording rules promotion to production explanation

fix: add recording rules promotion to production

---

rhobs/alerting/data_plane/prometheus.latency_pac_provision_alerts.yaml
rhobs/alerting/data_plane/prometheus.latency_release_creation_alerts.yaml
rhobs/alerting/data_plane/prometheus.latency_snapshot_to_static_integration_plr_creation_alerts.yaml
test/promql/tests/data_plane/latency_release_creation_test.yaml
test/promql/tests/data_plane/latency_snapshot_to_static_integration_plr_creation_test.yaml

Increasing alert **for** value to make trigering of alerts less sensitive.

feat(STONE-855): making alerts less sensitive

---

rhobs/alerting/data_plane/prometheus.pipeline_to_snapshot_alerts.yaml
test/promql/tests/data_plane/pipeline_to_snapshot_test.yaml

replace rhtap with konflux in gitlab url to redirect to correct page

Fix runbook URL in pipeline to snapshot alert

---

rhobs/recording/integration_service_availability_recording_rules.yaml
test/promql/tests/recording/integration_service_availability_recording_rules_test.yaml

* add recording rule for integration service availability
Signed-off-by: Hongwei Liu <hongliu@redhat.com>

feat(STONEINTG-955): add recording rule for intg availability

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

@amisstea fingers crossed PTAL .... I am trying to sanity check as well

chore: correct stage panel groupings

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml

@amisstea PTAL
@enarha @savitaashture @divyansh42 FYI

chore(SRVKP-4523): add tekton resolver deadlock panels/metric

---

rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
test/promql/tests/data_plane/pipeline_overhead_test.yaml

chore(SRVKP-6103,SRVKP-6104): set pipeline alert runbook urls; minor alert file reorg

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

fix: cleanup chain performance display unit, text

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
test/promql/tests/data_plane/pipeline_overhead_test.yaml

chore(SRVKP-4529): tekton results alerts, panels

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

fix: minor fix to deadlocked taskrun text

---

rhobs/alerting/data_plane/prometheus.availability_metric_integration_service_alerts.yaml
test/promql/tests/data_plane/availability_metric_integration_service.yaml

integration service availability metric
alert rule and alert test added

chore(stoneintg-1023): add IS SLO availability

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

1. Update RHTAP in title to Konflux
2. Update title to Integration Service SLOs
3. Fix the content in "Time to start Pipeline Run"
Signed-off-by: Raksha Rajashekar <rrajashe@redhat.com>

chore(PVCORE-4478): Update grafana-dashboard-rhtap-slos 

---

rhobs/recording/workspaces_service_availability_recording_rules.yaml
test/promql/tests/recording/workspaces_availability_recording_rules_test.yaml

feat(KONFLUX-2066): Adding recording rule for workspaces metric

---

rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml

This PR changes the runbook_url after the SRE docs PR is merged.
Signed-off-by: Divyanshu Agrawal [diagrawa@redhat.com](mailto:diagrawa@redhat.com)
/cc @mftb 
FYI @gabemontero

fix(SRVKP-6610): correct link to SRE docs and perform cleanup

---

.tekton/o11y-pull-request.yaml
.tekton/o11y-push.yaml

This became required on Nov 1st.

Add missing konflux task

---

dashboards/grafana-dashboard-productization-transparency.configmap.yaml

This is productization team 's poc dashboard for ADR-- productization transparency.  Thanks

productization poc dashboard

---

rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
test/promql/tests/data_plane/performance_test.yaml

This PR adds new set of alerts to monitor for performance anomalies for components like ETCD, Kube-API and Node.
Parent Story: https://issues.redhat.com/browse/KONFLUX-5411

feat(KONFLUX-5450): Adding alert rules to detect performance anomalies

---

rhobs/alerting/data_plane/prometheus.project_controller_up_alerts.yaml
test/promql/tests/data_plane/project_controller_up_test.yaml

Alert when project-controller is down

chore(KFLUXVNGD-137): add project-controller slo alert

---

README.md
rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
test/promql/tests/data_plane/performance_test.yaml

fix: Route performance alerts to the performance and scale team
Signed-off-by: Matheus Boy <mboy@redhat.com>

Routing performance alerts to the performance and scale team

---

dashboards/grafana-dashboard-konflux-availability-exporter.configmap.yaml

[PVO11Y-4565](https://issues.redhat.com/browse/PVO11Y-4565)

feat(PVO11Y-4565): Add degraded instances list

---

rhobs/alerting/data_plane/prometheus.cluster_capacity_alerts.yaml
test/promql/tests/data_plane/cluster_capacity_test.yaml

- Include database size alerts with different severities
- Include etcd no leader alert
- Include etcd change leader alert

Add new cluster etcd alerts 

---

rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
test/promql/tests/data_plane/performance_test.yaml

Normal Job duration on Konflux is 40 min. See linked issue.

feat(KONFLUX-7899): Make KubernetesLongRunningJob bit more permissive

---

rhobs/alerting/data_plane/prometheus.cluster_capacity_alerts.yaml
test/promql/tests/data_plane/cluster_capacity_test.yaml

- Updated cluster capacity etcd alert thresholds to enable tests.
- Updated etcd unit tests based on new thresholds.

Update etcd alert expression thresholds

---

dashboards/grafana-dashboard-cluster-capacity.configmap.yaml

- Add new dashboard with etcd and cluster capacity metrics.

feat(PVO11Y-4653): create cluster capacity dashboard

---

dashboards/grafana-dashboard-cluster-capacity.configmap.yaml

fix(PVO11Y-4653): Include label to cluster capacity dashboard

---

rhobs/alerting/data_plane/prometheus.cluster_capacity_alerts.yaml
test/promql/tests/data_plane/cluster_capacity_test.yaml

- Update insufficient members alert threshold

fix(PVO11Y-4656): Update insufficient members alert threshold

---

rhobs/recording/kubearchive_recording_rules.yaml

Starting PrometheusRule for KubeArchive

feat: Add KubeArchive konflux_up recording rule

---

rhobs/recording/mintmaker_service_availability_recording_rules.yaml
rhobs/recording/multi_platform_controller_availability_recording_rules.yaml
rhobs/recording/one_time_password_recording_rules.yaml
rhobs/recording/redis_service_availability_recording_rules.yaml
rhobs/recording/smee_service_availability_recording_rules.yaml
test/promql/tests/recording/multi_platform_controller_availability_recording_rules_test.yaml

Based on KFLUXVNGD-301, SPRE-1359, CWFHEALTH-4174 this PR is to creat the konflux_up metric for 
- MPC Controller
- OTP service
- Mintmaker controller
- Redis service
- smee client
konflux_up check is based on replica count
CC @jdcasey

feat(KFLUXVNGD-301, SPRE-1359, CWFHEALTH-4174): Konflux up metric

---

Dockerfile
config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml
exporter-build-scripts/entrypoint.sh
exporters/README.md

Allow to build more than one exporter and select the one to use using the "cmd" of the image.

feat(PVO11Y-4779): Dynamic multi-exporter build and runtime selection

---

dashboards/grafana-dashboard-cluster-capacity.configmap.yaml

- Updated graph descriptions
- Included alert rule links
- Included dashboard reference link
- Updated Overview graphs

fix(PVO11Y-4776): Update ETCD dashboard descriptions and formats

---

rhobs/recording/prometheus_availability_recording_rules.yaml
test/promql/tests/recording/prometheus_availability_recording_rules_test.yaml

New konflux_up metric to watch the watchers...

PVO11Y-4772 - konflux_up metric for the 3 Promtheus instances in each cluster

---

rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
test/promql/tests/data_plane/performance_test.yaml

fix(SPRE-1556): Routing High CPU and High memory node alerts to the new perfandspreandinfra route

fix(SPRE-1556): Routing High CPU and High memory node alerts to the new perfandspreandinfra route

---

rhobs/alerting/data_plane/prometheus.namespace_lister_alerts.yaml
test/promql/tests/data_plane/namespace_lister_test.yaml

Adding replica count slo alert based on https://issues.redhat.com/browse/SPRE-1528
CC @jdcasey

feat(SPRE-1528): namespace-lister slo replica count

---

rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
test/promql/tests/data_plane/release_service_test.yaml

Update availability query to expose cluster name.

feat(RELEASE-1431): add cluster information

---

dashboards/grafana-dashboard-rhtap-slos.configmap.yaml

Add project-controller SLOs to dashboard.

chore(KFLUXVNGD-300): project-controller SLO dash

---

rhobs/alerting/data_plane/prometheus.integration_service_availability_alerts.yaml
test/promql/tests/data_plane/integration_service_availability_test.yaml

changed alert to fire after 5 mins instead of 99% uptime edited alert tests to reflect new measurement

fix(stoneintg-1225): fixes for original file

---

rhobs/alerting/data_plane/prometheus.node_alerts.yaml
test/promql/tests/data_plane/node_alerts_test.yaml

- Include Master and Infra Node CPU and Memory usage alerts.

feat(SPRE-1486): Master and Infra Node alerts

---

dashboards/grafana-dashboard-konflux-integration-service.configmap.yaml

to display availability metrics (konflux_up) for all clusters

chore(stoneintg-1276): new integration service dashboard

---

rhobs/alerting/data_plane/prometheus.support_ops_availability_alerts.yaml
test/promql/tests/data_plane/support_ops_availability_alerts_test.yaml

Added altering rule and tests for Konflux support ops

chore(KFLUXSPRT-3662): SLO alerts for Konflux support-ops

---

rhobs/alerting/data_plane/prometheus.kueue_alerts.yaml
test/promql/tests/data_plane/kueue_alerts_test.yaml

KFLUXINFRA-2067: Add SLOs for Kueue

---

Dockerfile
rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
test/promql/tests/data_plane/release_service_test.yaml

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

fix: decrease check period to 1h

---

rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
test/promql/tests/data_plane/release_service_test.yaml

- Include cluster in release service alerts.

feat(SPRE-1875): Include cluster in release service alerts

---

dashboards/grafana-dashboard-konflux-integration-service-sli.configmap.yaml

from rh01 dash, convert to timeseries panels

task(stoneintg-1321): move heatmap panels to multi-cluster dash

---

dashboards/grafana-dashboard-konflux-integration-service-sli.configmap.yaml

include percentile info 50 95 and 99

task(stoneintg-1321): refine latency creation panel

---

dashboards/grafana-dashboard-konflux-kubearchive-slo.configmap.yaml
dashboards/grafana-dashboard-konflux-kubearchive-status.configmap.yaml

This PR addreses KAR-517 which should result in the inclusion of SLO dashboard for KubeArchive:
* Add KubeArchive SLO dashboard
* Add KubeArchive Status dashboard to help with the Failure Mode anlysis

Add KubeArchive SLO dashboard (KAR-517)

---

rhobs/recording/alert_count_recording_rules.yaml
test/promql/tests/recording/alert_count_recording_rules_test.yaml

Test Alert Count recording rule.
- New alert recording rules
- New alert test recording rules

Include Alert recording rule

---

dashboards/grafana-dashboard-konflux-prom-availability.yaml

[Adding Dashboards](https://issues.redhat.com/browse/PVO11Y-4775) describing the state of the various Prometheus instances in Konflux clusters.
Link to staging - https://grafana.stage.devshift.net/goto/pR3PI9jNg?orgId=1
---
---
---
Once your PR is ready please let us know in the [#forum-konflux-o11y](https://redhat.enterprise.slack.com/archives/C04FDFTF8EB) slack channel. Tag `@konflux-o11y-ic` for assistance.

PVO11Y-4775 - Prometheus SLO Dashboard
