redhat-appstudio/o11y

- prometheus/base/kustomization.yaml
- prometheus/base/namespaces.yaml
- prometheus/base/prometheus.rules.yaml
Adding dummy Prometheus recording rules to verify
o11y repository's infrastructure.
The expected behavior is that infra-deployments' ArgoCD instance should automatically deploy any PrometheusRules when there are new commits to the main branch of the 011y repository.
> chore(STONEO11Y-28): dummy Prometheus recordingRule resource

- .tekton/pull-request.yaml
- automation/promtool_tests.sh
- test/promql/tests/example.yaml
- test/promql/tests/example2.yaml
Change the test script to support also lint tests, and have the CI
trigger it once for testing the rules and once for test linting.
Depends on #9
> test(STONEO11Y-52): run promtool linter in ci

- .tekton/pull-request.yaml
Using the default depth of 1 required using unshallow later on.
This introduced flakiness as sometimes an error appears for
shallow file has changed since we read it.
With this change, we specifically fetch the target remote branch
and increase the depth of the PR branch which hopefully together
will work around the flakiness.
> fix(STONEO11Y-55): change git fetch command used before gitlint

- .tekton/push.yaml
In order to get updates in infra-deployments
for changes in the o11y repo, a PipelineRun
should be created on-push which use the
update script of infra-deployments.
> chore(STONEO11Y-28): deploy to infra-deployments on push

- prometheus/base/prometheus.rules.yaml
- test/promql/tests/test_network.yaml
This PR is for adding metric in the rule file that will assist us in getting the network egress (transmit)  
of all the containers, and to filter them by namespace or pipeline type
Adding a rule file with a `container_network_transmit_bytes_total` metric and attach the `label_pipelines_appstudio_openshift_io_type` to the result. 
This way we will be able to filter our results both by `namespace` and `label_pipelines_appstudio_openshift_io_type`  
The new metric is called `appstudio_container_network_transmit_bytes_total`
- To get the total amount of transmitted bytes in the last day, filtering by namespace:
`sum(increase(appstudio_container_network_transmit_bytes_total[1d])) by (namespace)`
- To get the total amount of transmitted bytes in the last day, filtering by pipeline type: …
> chore(STONEO11Y-21): add network egress metric and tests

- .tekton/pull-request.yaml
- Makefile
Run tests using makefile. This will allow developers running test prep steps together with the tests themselves using `make all`.
> chore(STONEO11Y-61): add makefile

- .gitignore
- .tekton/pull-request.yaml
- Makefile
- automation/pint_lint.sh
* pint installation have being moved from `pint_lint` to the Makefile. This saves a check if pint is already installed.
* Added pint to .gitignore
* Added pint to the makefile `all` target
> chore(STONEO11Y-63): Add pint to gitignore & install in Makefile

- .gitignore
- .tekton/pull-request.yaml
- Makefile
Add a test that verifies the configurations we have can be built with kustomize. This will prevent us from committing configs that will later fail deployment.
We can later on add a test that verifies the actual content of the yamls being generated. I wanted to add something simple to make sure the configs are buildable.
Making yaml comparisons is less trivial as it will require some sort of comparison that will not fail over ordering issues etc. I'm sure it can be done, but it will take some more effort in validation and I don't want to introduce flakiness hurrying to get this in.
> test(STONEO11Y-116): kustomize build passes

- CONTRIBUTING.md
On the last retrospective call, some team members raised a requirement that PR owners will provide some context to the PR within its description in order to facilitate the review process. This PR is updating the contributing guide accordingly.
Adding a paragraph to the contributing guide regarding PR description requirements. The idea is that contributors will provide some context to their PRs, so that reviewers work becomes more effective.
> chore: add PR description requirements to contributing guide

- prometheus/base/alerting/kustomization.yaml
- prometheus/base/alerting/prometheus.controller_alerts.yaml
- prometheus/base/alerting/prometheus.pod_alerts.yaml
- prometheus/base/recording/prometheus.rules.yaml
- test/promql/tests/test_controller_reconciliation_errors.yaml
Create an alerting rule for controller reconciliation errors and add related unit test cases.
> chore(STONEO11Y-96): Alerting rule for high controller reconciliation errors

- .tekton/pull-request.yaml
- CONTRIBUTING.md
- Makefile
- grafana/dashboards/.lint
- Add Grafana dashboard linting for all dashboards in the `grafana/dashboards` directory
- Add a `.lint` file in the `grafana/dashboards` directory with the rules to be excluded in the linting
> chore(RHTAPWATCH-163): Add dashboard linting to o11y CI

- prometheus/base/alerting/prometheus.argocd_alerts.yaml
- test/promql/tests/test_progressing_argocd.yaml
* An alert rule for argoCD apps which were in "Progressing" state in the past 20 minutes, and are still not healthy.
> chore(RHTAPWATCH-238): Alert rule for progressing argoCD apps

- prometheus/base/recording/prometheus.rules.yaml
- test/promql/tests/resource-min-labeling.yaml
- test/promql/tests/resource-min-sum.yaml
- test/promql/tests/test_network.yaml
* This is a second commit regarding RHTAPWATCH-110, the label "label_app_kubernetes_io_managed_by"
was added to appstudio_container_resource_limits.
* Added test cases.
> chore(RHTAPWATCH-110): Add "label_app_kubernetes_io_managed_by" label to recording rule

- prometheus/base/alerting/kustomization.yaml
- prometheus/base/kustomization.yaml
- prometheus/base/recording/kustomization.yaml
The Prometheus rules coming from the o11y repo should not be deployed to RHTAP using argoCD. Instead, they are to be deployed using app-interface.
Later on we might want to offboard the o11y component altogether
> chore(RHTAPWATCH-327): offboard o11y prometheus rules

- README.md
The README file was out of date as it was about content revolving around recording rules, which since then were removed from this repo.
This change removes that content and replaces it with instructions for maintaining alert rules.
> docs(RHTAPWATCH-328): update readme with rules procedures

- rhobs/alerting/prometheus.pod_alerts.yaml
- test/promql/tests/test_crashloopbackoff.yaml
- test/promql/tests/test_unschedulable_pods.yaml
Adding link to SOPs to alerts CrashLoopBackOff and UnschedulablePods to provide instructions for dealing with those alerts.
> chore(RHTAPWATCH-346 RHTAPWATCH-347): add sop links to 2 pod alerts

- .tekton/pull-request.yaml
- Makefile
- prometheus/base/kustomization.yaml
- prometheus/base/namespaces.yaml
* The o11y namespace definition and all kustomization files should be removed from the o11y repo
* The [prometheus/base path](https://github.com/redhat-appstudio/o11y/tree/main/prometheus) should be removed and the kustomize build test should be removed from the makefile and the [CI file](https://github.com/redhat-appstudio/o11y/blob/main/.tekton/pull-request.yaml).
* kustomize installation should be removed from local tests and CI.
> chore(RHTAPWATCH-334): Remove the o11y namespace resource definition from the o11y repo

- README.md
- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
app-interface will be configured to pull the dashboard ConfigMaps from the dashboards/ directory and deploy them to AppSRE's grafana.
Other teams are expected to update this dashboard as they contribute SLOs. The barebones version looks like this:
> feat(RHTAPWATCH-452): Add initial grafana dashboard for SLOs

- rhobs/alerting/prometheus.application_alerts.yaml
- test/promql/tests/application_errors_test.yaml
Adds an alerting rule for the [Application Deletion SLO](https://docs.google.com/document/d/1OVVZeCmv6o2qsZ1BhPaVPVzkJSa8cxLAN5ImF1eugOE/edit): 99% of Application deletion requests must succeed. 
I've also added test cases for the alert rule, which test the following:
- 100%, 10%, and 5% failing deletions should all alert
- 1% failed deletions should not alert
> chore(DEVHAS-452): Alerting rule for Application deletion SLO

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
This PR adds a very basic visualization of the Application Deletion SLO: [99% of deleted applications must succeed](https://docs.google.com/document/d/1OVVZeCmv6o2qsZ1BhPaVPVzkJSa8cxLAN5ImF1eugOE/edit#bookmark=id.xouxmpbq76k4) to the Grafana dashboard.
> chore(DEVHAS-452): Add visualization for application deletion SLO

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
It seems as the ProgressingArgocdApp rule is not loaded correctly to RHOBS due to the for field set to 0m. Setting it to 1m to work around that.
> fix: add positive for-value to progressing argo app rule

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
- test/promql/tests/control_plane/argocd_test.yaml
The control plane alerts contained severity `medium` which is not one of the values supported by PagerDuty, which caused errors in RHOBS. This change addresses that.
> fix(RHTAPWATCH-523): control plane alerts unsupported severity

- .tekton/pull-request.yaml
- Makefile
- config/probes/monitoring/grafana/base/kustomization.yaml
- config/probes/monitoring/grafana/base/namespace.yaml
Create a namespace to be used by a probe that will monitor the Grafana deployment.
This is how the namespace will be used: https://github.com/redhat-appstudio/infra-deployments/pull/2454
> chore(RHTAPWATCH-518): create grafana probe namespace

- config/probes/monitoring/grafana/base/grafana-datasource-probe.yaml
- config/probes/monitoring/grafana/base/kustomization.yaml
This PR is for both RHTAPWATCH-404 and RHTAPWATCH-517 for creating an example probe and a service account. Our probe checks if our datasource is available in Grafana Job will fail if it does not exist
> chore(RHTAPWATCH-404): create an example probe

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
This PR adds a visualization to the RHTAP SLO dashboard for the Application creation SLO:
"95% of created applications must succeed"
> chore(DEVHAS-481): Add visualization for the Application creation SLO

- rhobs/alerting/data_plane/prometheus.application_alerts.yaml
- test/promql/tests/data_plane/application_errors_test.yaml
This PR adds alerting rules for the Application creation SLO as found [here](https://docs.google.com/document/d/1OVVZeCmv6o2qsZ1BhPaVPVzkJSa8cxLAN5ImF1eugOE/edit#bookmark=id.78n0do63qmep) (95% of created applications should have succeeded)
Corresponding alert tests have also been added
> chore(DEVHAS-481): Add alerting rules for the Application creation SLO

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
Issue - As my recent PR got merged [PR](https://github.com/redhat-appstudio/o11y/pull/96 ), I was checking the metrics panel in grafana dashboard, but I found this issue 
- Whenever I tried to click edit/view in this right panel as shown here :
- It is redirecting me to this panel : 
- and whenever I tried clicking edit/view on left panel as shown here : 
- it is giving this error(permission denied which you can see in top right hand corner)
- I think this happend because of rebase and Id has been mismatched, fixed that in this PR and it is working fine and as expected:
> fix(GITOPSRVCE-753): Fix grafana dashboard for Gitops Service SLO for cluster-agent panel

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
This PR is to add 6 new panels for GitOps Service SLOs.
https://issues.redhat.com/browse/GITOPSRVCE-751
Here is the screenshot of them.
> feat(GITOPSRVCE-751): Add SLO visualizations for the Argo CD resources

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
This adds the pipeline service alert slo panels to the dashboard:
> chore(PLNSRVCE-1470): add pipeline service SLO row/panels to RHTAP app-sre SLO dashboard

- rhobs/alerting/data_plane/prometheus.serviceprovider_alerts.yaml
- test/promql/tests/data_plane/serviceprovider_errors_test.yaml
As part of RHTAP/SPI SRE onboarding, added the alert for number of 5xx responses from service providers.
> chore(SVPI-644): Add alert  for 5xx responses rate from SP

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
- test/promql/tests/control_plane/argocd_test.yaml
The metric currently used for the control plane alerts is also going to be forwarded from the data plane clusters to allow some other alerts.
With this change, we specify the exact namespace for the control plane alerts so they don't trigger on metrics coming from other namespaces.
> chore(RHTAPWATCH-514): limit namespace for control plane alerts

- Dockerfile
Dockerfile is added to the o11y repo to build the docker image for the prometheus exporters.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-578
> feat(RHTAPWATCH-578): write Dockerfile for exporter service

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
During the definition of the accompanying pipeline service alerts we settled on using 'increase' instead of 'sum_over_time' to better deal with metric controller restarts.  Adjusting ccompanying grafana panels accordingly.
@redhat-appstudio/o11y PTAL
> chore(PLNSRVCE-1470): adjust pipeline service grafana panels to switch from 'sum_over_time' to 'increase' to match alerts

- Dockerfile
Added commands to update libcurl in Dockerfile to mitigate the vulnerabilities in quay container registry.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-579
> chore(RHTAPWATCH-579): Update libcurl in Dockerfile

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.application_alerts.yaml
- test/promql/tests/data_plane/application_errors_test.yaml
As part of the fix for [DEVHAS-547](https://issues.redhat.com/browse/DEVHAS-547), the HAS team has decided to adjust down the "Application Deletion" SLO from 99% to 95%. This PR updates the Prometheus alerts and Grafana dashboard accordingly
> chore(DEVHAS-547): Bump down Application deletion SLO to 95%

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
Updated grafana dashboard for cluster-agent slos, updated the query, aggregated `operationDB_rows_in_non_complete_state` based on source_cluster and updated based on the comments in my PR https://github.com/redhat-appstudio/o11y/pull/117
> feat(GITOPSRVCE-753): Update cluster-agent slo dashboard

- rhobs/alerting/data_plane/prometheus.latency_release_creation_alerts.yaml
- test/promql/tests/data_plane/latency_release_creation_test.yaml
add alert for snapshot marked as passed to
release created where >10% of requests takes
longer than 10s
Add alert testing, 3 cases with 2 clusters each:
Where neither cluster triggers alert
Where one cluster triggers alert
Where both clusters trigger alert
> feat(STONEINTG-561): add alert IS SLO 5

- rhobs/alerting/data_plane/prometheus.gitops_statefulsets_alerts.yaml
- test/promql/tests/data_plane/gitops_statefulsets_test.yaml
This PR is to add alert rules and their tests for StatefulSets SLOs added by GitOps Service team.
https://issues.redhat.com/browse/GITOPSRVCE-751
> feat(GITOPSRVCE-751): Add alert rule/test for StatefulSets SLO

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
Add a new visualization for Argo CD reconciliation performance
Jira: [GITOPSRVCE-752](https://issues.redhat.com/browse/GITOPSRVCE-752)
Screenshot:
> feat(GITOPSRVCE-752): Add Argo CD reconciliation chart

- rhobs/alerting/data_plane/prometheus.gitops_routes_alerts.yaml
- test/promql/tests/data_plane/gitops_routes_test.yaml
This PR is to add alert rules and their tests for Routes SLOs added by GitOps Service team.
https://issues.redhat.com/browse/GITOPSRVCE-751
> feat(GITOPSRVCE-751): Add alert rule/test for Route SLO

- rhobs/alerting/data_plane/prometheus.component_alerts.yaml
- test/promql/tests/data_plane/component_errors_test.yaml
This PR:
* Similar to component deletion, adds component component creation alerting rules and tests.
* Fixes the runbook links for the component deletion rules.
> chore(DEVHAS-571): Add component creation alerting rules and tests

- config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml
Updated the image tag used in the deployment resource to fix the kube linting issue.
> chore: fix kube linting issue for exporters image

- .gitlint
gitlint now ignores commits made by dependabot and red-hat-trusted-app-pipeline as those are usually
invalid (either have long lines or do not sign off commits)
> chore: gitlint ignores bot users

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
After moving to custom build pipeline o11y existing checks are removed. So, adding existing checks to the new pipeline.
> chore(RHTAPWATCH-563): Update o11y pipeline checks in custom build

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
add SLO alert rules for the Release Service
- ReleaseServiceProcessingDuration:
90% of the releases should be processed under 1 hour
- ReleaseServiceStartProcessingSeconds:
90% of the releases should start processing under 10 seconds
- ReleaseServiceValidationSeconds:
90% of the releases should be validated under 5 seconds
Signed-off-by: Leandro Mendes <lmendes@redhat.com>
> chore(RHTAPREL-304): add alerting for release service SLOs

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
- rhobs/alerting/data_plane/prometheus.gitops_argocd_app_reconcile_alerts.yaml
- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- test/promql/tests/control_plane/argocd_test.yaml
- test/promql/tests/data_plane/crashloopbackoff_test.yaml
- test/promql/tests/data_plane/gitops_argocd_app_reconcile_test.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
- test/promql/tests/data_plane/unschedulable_pods_test.yaml
Adds a "namespace" annotation to all `pod alerts` alerts,
and to `rhtap-gitops-argocd-app-reconcile-alert` alert.
This is used to test a future feature that will tag the team
relevant to the alert where the alert is recieved.
Alert recievers doesn't have access to the prometheus labels,
therefor the label has to be added to the alert itself, which
the reciever can access.
Although the "namespace" is available on some alerts as a default
label, adding it as an annotation for uniformity and readability sake.
> chore(RHTAPWATCH-530): namespace annotation on pod alerts

- rhobs/always_firing.yaml
- test/promql/tests/always_firing_test.yaml
Adds an alert that always firing in order to test the slack tagging logic sooner than later.
Will probably change the annotation more later to
test different cases.
> test(RHTAPWATCH-637): always-firing alert to test tagging logic

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
- test/promql/tests/control_plane/argocd_test.yaml
Adding a `summary` annotation and rename the `message` annotation to `description` to be alligned with all the alerts in `o11y` and to make it easier to extract these values when we route the alerts.
> chore(RHTAPWATCH-675): Update annotations for control_plane alerts

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- rhobs/alerting/data_plane/prometheus.pv_alerts.yaml
- rhobs/alerting/data_plane/prometheus.quota_alerts.yaml
- test/promql/tests/data_plane/crashloopbackoff_test.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
- test/promql/tests/data_plane/quota_exceeded_test.yaml
- test/promql/tests/data_plane/unschedulable_pods_test.yaml
This should reduce exessive alert noise originating from namespaces used to build and test Konflux components.
> fix(RHTAPWATCH-739): ignore tekton-ci and build-definitions-e2e

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- rhobs/alerting/data_plane/prometheus.pv_alerts.yaml
- rhobs/alerting/data_plane/prometheus.quota_alerts.yaml
- test/promql/tests/data_plane/crashloopbackoff_test.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
- test/promql/tests/data_plane/quota_exceeded_test.yaml
- test/promql/tests/data_plane/unschedulable_pods_test.yaml
This corrects a simple mistake from RHTAPWATCH739.
> fix(RHTAPWATCH-757): Don't monitor the build-templates-e2e namespace

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
Updates the HAS Component Create SLO Panel to include a 1hr time window. The alerts are over a 1h period as well.
This is how it looks in the dashboard. I copy pasted the property from the JSON:
> chore: Add time frame for HAS Component Create SLO Panel

- rhobs/alerting/data_plane/prometheus.backup_alerts.yaml
- test/promql/tests/data_plane/backup_failed_test.yaml
The `runbook_url` doesn't exist yet but will be created separately as part of [RHTAPSRE-320](https://issues.redhat.com/browse/RHTAPSRE-320).
> feat(RHTAPWATCH-692): Add BackupFailed alerting rule

- rhobs/alerting/data_plane/prometheus.pipeline_to_snapshot_alerts.yaml
- test/promql/tests/data_plane/pipeline_to_snapshot_test.yaml
* The alert is currently flaky and flapping because of different services taking longer to finalize the build pipelineRuns
* See also [KFLUXBUGS-24](https://issues.redhat.com/browse/KFLUXBUGS-24)
> fix(STONEINTG-777): extend the window for PipelineRunToSnapshotExceeded

- Dockerfile
Added labels to the Dockerfile to mitigate the violation labels.disallowed_inherited_labels and make the EC checks pass.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-840
> chore(RHTAPWATCH-840): Update Dockerfile to pass EC checks

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
- Dockerfile
Added labels to the Dockerfile to mitigate the violation labels.disallowed_inherited_labels.
Updated the default value for source-build to make the EC checks pass.
> chore(RHTAPWATCH-840): Update Dockerfile and .tekton to pass EC checks

- README.md
- exporters/dsexporter/README.md
- Add README.md under o11y/exporter/dsexporter/
- Add blub about exporters in the root README.md
> chore(RHTAPWATCH-592): Create a README in o11y/exporter/dsexporter/ and add blurb about exporters in the root README

- .tekton/o11y-pull-request.yaml
Using branch name causes EC to fail. Using commit sha instead
> fix: use sha instead of branch name for clone-repo step

- Makefile
- exporters/dsexporter/dsexporter.go
- rhobs/recording/exporter_recording_rules.yml
- test/promql/tests/recording/exporter_recording_rules_test.yml
Add recording rules to translate the components existing metrics to expose availability.
> chore(RHTAPWATCH-741): Add recording rules for exporter

- rhobs/alerting/data_plane/prometheus.latency_release_creation_alerts.yaml
- rhobs/alerting/data_plane/prometheus.latency_snapshot_to_static_integration_plr_creation_alerts.yaml
- test/promql/tests/data_plane/latency_release_creation_test.yaml
- test/promql/tests/data_plane/latency_snapshot_to_static_integration_plr_creation_test.yaml
Change the integration team group to S05M4AG8CJH to their request.
> chore: replace integration team alert tagging

- README.md
Add recording rule documentation to the
README
> docs: Add recording rule documentation

- dashboards/argocd/grafana-dashboard-stonesoup-argocd.configmap.yaml
This will add a `configmap` to be used in app-interface configuration to create a Grafana dashboard.
> chore(RHTAPSRE-437): Adding Control Plane ArgoCD Dashboard

- rhobs/recording/remotesecret_availability_recording_rules.yaml
- test/promql/tests/recording/remotesecret_availability_recording_rules_test.yml
Transform existed `redhat_appstudio_remotesecret_secretstorage_system_available` metric to the form `onflux_up(service="remote-secret-controller-manager-metrics-service", check="secretstorage")`
> Remotesecret availability mertic rule

- rhobs/alerting/control_plane/prometheus.argocd_alerts.yaml
- test/promql/tests/control_plane/argocd_test.yaml
Update `alert_routing_key` to be assigned with the application name instead of namespace in ArgoCD alerts
> chore(RHTAPWATCH-794): update alert_routing_key in argocd alerts

- rhobs/recording/has_recording_rules.yaml
- test/promql/tests/recording/has_recording_rules_test.yml
https://issues.redhat.com/browse/DEVHAS-598
Recording Rule for the [HAS Availability metrics](https://github.com/redhat-appstudio/application-service/pull/453)
```
has_availability(check=github) -> konflux_up(service=has, check=github)
```
> fix(DEVHAS-598): Add in HAS recording rules for availability metrics

- Dockerfile
- config/exporters/monitoring/grafana/base/prometheus-exporter-service-monitor.yaml
- config/exporters/monitoring/grafana/base/prometheus-exporter-service.yaml
Updating the rolebinding to clusterrolebinding to make the exporter
work after authentication and prioritize namespace to create first.
Updated the ubi-minimal image to ubi-micro to make integration
test pass.
> chore(RHTAPWATCH-891): Update rolebinding to clusterrolebinding

- README.md
- rhobs/alerting/data_plane/prometheus.availability_metric_grafana_alerts.yaml
- rhobs/alerting/data_plane/prometheus.availability_metric_has_alerts.yaml
- rhobs/alerting/data_plane/prometheus.availability_metric_remotesecret_alerts.yaml
- test/promql/tests/data_plane/availability_metric_grafana_test.yaml
- test/promql/tests/data_plane/availability_metric_has_test.yaml
- test/promql/tests/data_plane/availability_metric_remote_secret_test.yaml
Added alerting rule and related promql unit tests
for konflux_up metric.
Jira-Url:https://issues.redhat.com/browse/RHTAPWATCH-890
> chore(RHTAPWATCH-890): Add Alering Rule for konflux_up metric

- rhobs/recording/build_service_availability_recording_rules.yaml
- rhobs/recording/image_controller_availability_recording_rules.yaml
- test/promql/tests/recording/build_service_availability_recording_rules_test.yaml
- test/promql/tests/recording/image_controller_availability_recording_rules_test.yaml
Transform existing `redhat_appstudio_buildservice_global_github_app_available` and `redhat_appstudio_imagecontroller_global_quay_app_available`  into
to the form `konflux_up(service="build-service-controller-manager-metrics-service", check="github")` and
`konflux_up(service="image-controller-controller-manager-metrics-service", check="quay")`
> Build-service availability mertic rules

- dashboards/availability_exporter.json
- Add graph for individual availability probes
- Add the availability of each Konflux component
- Add the availability of all of Konflux
**Grafana Dashboard:** https://grafana.stage.devshift.net/d/fdifr5mbapv5sb/availability-exporter-dashboard?orgId=1
**Ticket:** [RHTAPWATCH-897](https://issues.redhat.com/browse/RHTAPWATCH-897)
**Screenshot:**
> chore(RHTAPWATCH-897): Availability exporter dashboard

- rhobs/alerting/data_plane/prometheus.availability_metric_konflux_alerts.yaml
- test/promql/tests/data_plane/availability_metric_konflux_test.yaml
This alert rule checks if konflux_up metric is available over all the clusters
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-954
> chore(RHTAPWATCH-954): Alert rule to check konflux_up metric

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
> fix(KFLUXBUGS-1248): invert pipeline service alerts to >0.95 percentile

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
since we went from <query> to "1 - <query>" we had to flip the threshold base and colors so that it is green if 95 or above and red if below 95
rh-pre-commit.version: 2.2.0
> fix(KFLUXBUGS-1248): adjust panel threshold to match query

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
- Add 'runbook_url' to Release service Prometheus urls
> fix(KFLUXBUGS-1272): Broken URLs in slo-documents of Konflux services

- rhobs/alerting/data_plane/prometheus.stability_image_repository_provision_alerts.yaml
- rhobs/alerting/data_plane/prometheus.stability_simple_build_alerts.yaml
- test/promql/tests/data_plane/stability_image_repository_provision_test.yaml
- test/promql/tests/data_plane/stability_simple_build_test.yaml
This PR changes the following SLO alerts:
- Build Service simple build: since simple builds are not often used, even one failure would trigger alert. Increasing thresholds to be less sensitive.
- Image Controller: sometimes Quay stability is not ideal and we shouldn't alert at the first failure. Increasing threshold to 20% since the operation is not often performed (the same for the time period).
> chore(build team SLOs) Correct Build Team SLO alerts

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
There are a number of untrusted tasks in the CI pipeline that trigger failures in the EC integration pipeline. The EnterpriseContractPolicy requires all tasks to be trusted unless operating with OCI trusted artifacts. When using trusted artifacts, EC should not raise violations for tasks which are not involved in creating an artifact.
> fix: use OCI trusted artifacts in CI

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
Many of these alerts are auto resolving shortly after the 15m window. Increasing this to 30m in an effort to reduce alert fatigue.
> fix: reduce sensitivity of the PodsNotReady alerting rule

- .tekton/kube-linter-oci-ta.yaml
- .tekton/o11y-pull-request.yaml
This pull request changes the Tekton Pipelines to use Trusted Artifacts to share data between its Tasks. The main benefit is the assurance that the output of one Task is consumed by another Task without having been modified. This enables a more fine-grained validation by the Enterprise Contract. Not every Task in the Pipeline needs to be trusted, just the ones involved in building the image.
From the GitHub checks, you can see that the existing Enterprise Contract policy passes for the image built as part of this pull request. But that's not saying much because the policy currently exclude things like `trusted_task.trusted`.
I have verified that EC validation also passes for an even more restrictive policy:
```yaml
publicKey: |
-----BEGIN PUBLIC KEY----- …
```
> Use trusted artifacts

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
I'll add the panels once https://github.com/redhat-appstudio/infra-deployments/pull/4105 and I can test the changes against app-sre staging
this also replaces https://github.com/redhat-appstudio/o11y/pull/297 as I am pulling in the rest of the alerts I have planned for SRVKP-4523 @zanssa 
> SRVKP-4523: add alert,panels for tekton-pipeline-controllers deadlocks and rapid restarts

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
Factor k8s quota and node throttling into task controller deadlock alert. Correlation often exists given the one to one coupling between pods and TaskRuns.
> chore(SRVKP-4532): factor k8s throttling into task alert

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
`@plnsrvce-team` is getting deprecated/removed and the openshift-pipelines team want to now use `@pipelines-ic`
@enarha @savitaashture FYI
> chore: change pipeline related slack handle in alerts

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
expanding the restart alert to handle all `tekton-` pods in `openshift-namespace` given the recent trouble with the remote-resolver deployment 
we'll handle PAC and Results (especially given the memory leak) separately
@amisstea PTAL
@gbenhaim @zanssa @enarha  @divyansh42 @savitaashture FYI
> chore(SRVKP-4532): expand tekton restart alert

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
(re) add the panels for pipelinerun and taksrun deadlock alerts
@amisstea PTAL
@divyansh42 @khrm @savitaashture FYI and PTAL if you can
> chore(SRVKP-4532): pipeline/task deadlock panels

- rhobs/recording/release_service_availability_recording_rules.yaml
- test/promql/tests/recording/release_service_availability_recording_rules_test.yaml
This commit adds availability record rules and tests for the release-service availability metrics.
> feat(RELEASE-996): availability metrics for release-service

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
These are the alerts, panels, and alert unit tests for determining if tekton chains controller is either deadlocked or experiencing abnormally poor performance.
> chore(SRVKP-4527): alert/panels chain deadlock/performance

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
This commit removes the release_processing_duration SLO from alerting and dashboard as for the current moment the metrics available in this sensor can not be trusted as releases can have different processing time for different users.
> fix(RELEASE-1031): remove release_processing_duration SLO

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
Failed to catch with PR #341 that the alert actually did need to be switched from the 1 second 'le' bucket to the 10 second 'le' bucket as well.
> fix: cleanup chains performance alert, test

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
These are the alerts, panels, and alert unit tests for determining if tekton pac controller is either deadlocked or experiencing abnormally poor performance.
> chore(SRVKP-4528): alert/panels pac deadlock/performance

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
- Filter out the the konflux-ci namespace
> fix(RHTAPWATCH-1170): Filter out the the konflux-ci namespace in the PodNotReady alerting rule

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
Per discussions with @amisstea @divyansh42 here is the panel update which moves the slo template back to the bottom, and fixes some of the pipeline service panel groupings after all the (relatively) concurrently panel merges between my PRs and @divyansh42 's
Also
- there was a regexp tweak to the restart query that got list with @amisstea 's rebase of @divyansh42 's PR ... put that back in
- some of the results go to read threshold values were more aggressive than what we have in the alerts themselves
- also forgot that the default range is 28 days for the panels, where the new alerts or more in the 75 minute window; as a result, history from using `sum(increase(...)` that we were guided to doing for the alerts actually paint a more …
> fix: post merge pipeline svc panel tweaks

- README.md
The README had some outdated content. Updating...
> docs(RHTAPWATCH-1261): updating README

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
this commit adds new alerts for a new Release Service SLO namely ReleaseServiceControllerManagerAvailability.
> feat(RELEASE-1031): define alerts for Release availability

- rhobs/alerting/data_plane/prometheus.availability_metric_konflux_alerts.yaml
- test/promql/tests/data_plane/availability_metric_konflux_test.yaml
The konflux_up metric had a routing key which did not correspond to any routing rule in app-interface. Here we change it to a value that corresponds to an existing routing statement.
> chore: update konflux_up alert routing

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
this commit fixes the query that fetches the availability data, by ignoring duplicate data
and not counting data with value 0.
> fix: fixing availability query

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
this commit decreases the observation period and
moves the aggregation function back to sum.
testing historical data for the observation, this
query seems to be the most accurate so far conside-
ring the eventual occurence of the service in clusters not releasing.
Signed-off-by: Leandro Mendes <lmendes@redhat.com>
> fix: SLO alert improvement

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
OK in https://redhat-internal.slack.com/archives/C04TL3Q3C4B/p1727684817738179?thread_ts=1726251504.848259&cid=C04TL3Q3C4B and discussion with @jmicanek from Konflux SRE we confirmed non SRE/SLO alerts were allowed
So minimally we are removing the chains/pac perofrmance alerts/panels from the SRE list
However, the openshift pipelines team as part of discussion of https://issues.redhat.com/browse/SRVKP-4521 in https://redhat-internal.slack.com/archives/CG5GV6CJD/p1727717932286499 have misgivings around the Konflux alerts.
While I will allow them to continue discussions with Konflux monitoring / Konflux SRE on what to do there, but minimally, the chains/pac performance alerts previously approved by Konflux SRE as part of SRVKP-4521 should be removed from the equation.
This PR does this for …
> chore: remove pipeline performance alert,panels from slos, url cleanup

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
I noticed that the PipelinePodsRepeatedRestarts alert has a problem: at first, when pods are restarting, it fires. Good! But then, after a short while, the pod enters CrashLoopBackOff and it starts restarting less frequently. This causes PipelinePodsRepeatedRestarts to stop firing, making it appear as if the outage has resolved itself, when in fact it hasn't.
Adding this second alert will cause a second alert to fire when the situation cements itself into a CrashLoopBackOff.
Perhaps we should just remove the PipelinePodsRepeatedRestarts alert and replace it with this second one? Or - we could try both for a while and see how they play together before deciding?
> Add a crashloopbackoff alert for tekton

- rhobs/recording/multi_platform_controller_availability_recording_rules.yaml
- test/promql/tests/recording/multi_platform_controller_availability_recording_rules_test.yaml
Add transformer for `multi_platform_controller_available` metric.
> feat(KFLUXINFRA-987): Add MPC availability metric transformer

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
this PR change the release's controller SLO alert to consider only the clusters used for releasing software, namely stone-prd-rh01 and stone-prod-p02.
> fix: release SLO alert should consider clusters in use

- rhobs/alerting/data_plane/prometheus.build_service_alerts.yaml
- rhobs/alerting/data_plane/prometheus.image_controller_alerts.yaml
- test/promql/tests/data_plane/github_app_test.yaml
- test/promql/tests/data_plane/quay_failure_test.yaml
Jira: [STONEBLD-2651](https://issues.redhat.com/browse/STONEBLD-2651)
Add availability metrics for the build team which fire after five minutes of not having the `konflux_up` parameter
- Add GitHubAppFailureAlert for build-service
- Add QuayFailureAlert for image-controller
The alerts include `runbook_url` to currently non-existing SOPs. There is a [MR open which adds the SOPs](https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/179), but it's not yet merged (will mark this PR ready for review after it's merged)
> add build team availability alerts

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
change function sum to count to avoid duplication
of clusters after outage, causing the alert to take too long to clear
> fix: sum to count on release availability

- rhobs/alerting/data_plane/prometheus.release_service_alerts.yaml
- test/promql/tests/data_plane/release_service_test.yaml
This commit adds a new alert when the Release
Controller Manager Pod is in Not Ready state.
In addition it also changes the SLO alert for a 24h period, for less sensitivity.
> fix: add Pod alert and change SLO to 1d

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
This is related to https://github.com/redhat-appstudio/o11y/pull/411
In that PR, we added a new alert that fires when pods are in crashloopbackoff for more than 3 minutes. If they enter that state, something is definitely down.
The alert being modified in this change fires whenever pods restart more than once in a short period. Today, I observed this fire when the remote resolver controller pods all restarted a few times at the same time (4 pods, 2-3 restart each). They immediately recovered and began working happily. No perceived outage for users as far as I can tell.
If I understand that situation correctly, it means that this isn't really an SLO. It's more like a warning that can let us know if things are about to enter sustained crashloop backoff.
> feat: demote the pipeline pod restart alert to a warning

- dashboards/grafana-dashboard-productization-transparency.configmap.yaml
This should resolve the dashboard not showing up in grafana
Signed-off-by: Paul Cho <pacho@redhat.com>
> fix: Fix JSON error in productization transparency dashboard

- rhobs/recording/project_controller_availability_recording_rules.yaml
- test/promql/tests/recording/project_controller_availability_recording_rules_test.yaml
Create a recording rule that translates the ratio between available replicas and spec replicas to project-controller's konflux_up metric.
> chore(KFLUXVNGD-136): record project-controller availability

- rhobs/alerting/data_plane/prometheus.availability_metric_integration_service_alerts.yaml
- test/promql/tests/data_plane/availability_metric_integration_service.yaml
Re-enable the integration service availability SLO alert set to 'High' to reflect lack of SOP available.
> chore(STONEINTG-1053): downgrade Availability SLO alert to warning

- rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
- test/promql/tests/data_plane/performance_test.yaml
This PR increases the threshold limit for the ETCD alerts to **40ms** - **EtcdFsyncLatency** and **EtcdCommitLatency**.
Parent Story: https://issues.redhat.com/browse/KONFLUX-5411
> feat(KONFLUX-5411): Increase alert limits for EtcdFsyncLatency and EtcdCommitLatency

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
- test/promql/tests/data_plane/pipeline_leases_distribution_test.yaml
Fix routing to have correct routing variable for non slo alerts from pipeline alerts, not to ping o11y. 
Signed-off-by: Tomas Behal [tbehal@redhat.com](mailto:tbehal@redhat.com)
> fix(PVO11Y-4589): fix routing variable for pipeline alerts

- rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
- test/promql/tests/data_plane/performance_test.yaml
Add info about cluster (using `source_cluster` label) to performance alert description.
> feat(KONFLUX-6427): update perf alert description

- rhobs/alerting/data_plane/prometheus.latency_release_creation_alerts.yaml
- rhobs/alerting/data_plane/prometheus.latency_snapshot_to_static_integration_plr_creation_alerts.yaml
- test/promql/tests/data_plane/latency_release_creation_test.yaml
- test/promql/tests/data_plane/latency_snapshot_to_static_integration_plr_creation_test.yaml
* Downgrade `Latency Release creation` alert to high to reflect the lack of SRE-actionable SOP
* Downgrade `Latency Snapshot to PLR created` alert to high to reflect the lack of SRE-actionable SOP
Signed-off-by: dirgim <kpavic@redhat.com>
> chore(STONEINTG-1042): downgrade integration alerts

- .tekton/kube-linter-oci-ta.yaml
Use a newer version of kube-linter and switch over to ghcr.io to avoid issues with rate limits.
Signed-off-by: Paul Cho <pacho@redhat.com>
> ci: Update kube-linter container image

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
Removing  JAVA_COMMUNITY_DEPENDENCIES
> Removing JAVA_COMMUNITY_DEPENDENCIES from result, migration of buildah task from .2 to .3

- rhobs/alerting/data_plane/prometheus.eaas_alerts.yaml
- test/promql/tests/data_plane/eaas_test.yaml
Depends on:
- https://github.com/redhat-appstudio/infra-deployments/pull/5596
- https://gitlab.cee.redhat.com/konflux/docs/sop/-/merge_requests/265
> feat(KFLUXVNGD-197): Add HypershiftAWSQuotaAlmostFull alerting rule

- Dockerfile
The go-toolset builder image changed the directory perms of /usr/bin in 1.22 to remove the group writable bit.  This causes the mintmaker proposed changes to fail as go can not compile the 'exporters' binary into /bin (symlinked to /usr/bin).  This change writes the exporter binary to /tmp during compilation and then copies it to the image.
> fix: unblock mintmaker update to go-toolset due to change in dir perms

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- test/promql/tests/data_plane/notready_pods_test.yaml
mintmaker runs pipelineruns for users within its own namespace, these pipelineruns are renovate jobs, we don't need to be alerted about such errors.
> chore: ignore PodNotReady alerts in mintmaker namespace

- rhobs/recording/namespace_lister_availability_recording_rules.yaml
- test/promql/tests/recording/namespace_lister_availability_recording_rules_test.yaml
Add a `konflux_up` metric for namespace-lister, which is a dependency of the new UI for konflux.
See [ASC-803](https://issues.redhat.com/browse/ASC-803) for details.
> feat(KONFLUX-4930): add availability rule for namespace-lister

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipeline_deadlock_crashloop_test.yaml
- test/promql/tests/data_plane/pipeline_overhead_test.yaml
Changed alert name to ChainsControllerOverhead. Updated the alert conditions by increasing the threshold from 50 to 100 and reducing the required duration from 75m to 45m. This change aims to improve the alert's precision by reducing false positives and ensuring that only more critical cases trigger alerts. This change aims to improve precision by reducing false positives and ensuring that only critical cases trigger alerts.
> chore: name and condition change for ChainsControllerDeadlock alert

- rhobs/alerting/data_plane/prometheus.namespace_lister_alerts.yaml
- test/promql/tests/data_plane/namespace_lister_test.yaml
For now, we're only interested in monitoring when synchronizations fail and when we consistently return 500s.  We may add more alerts in the future.
> add initial alerting rules for namespace-lister

- .tekton/o11y-pull-request.yaml
- .tekton/o11y-push.yaml
Info about SAST Checks here - https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/conforma/new-sast-tasks-mar25.md. 
The [konflux-pipepine-patcher](https://github.com/simonbaird/konflux-pipeline-patcher) script was used to add the new tasks.
> Add sast checks

- rhobs/alerting/data_plane/prometheus.performance_alerts.yaml
- test/promql/tests/data_plane/performance_test.yaml
Also make it fire only once no matter on what etcd pod it will trigger. Screenshots attached to linked issue.
> feat(KONFLUX-7901): Make EtcdProposalFailures more permissive

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
- test/promql/tests/data_plane/exceeding_requested_resources_test.yaml
[PVO11Y-4645](https://issues.redhat.com/browse/PVO11Y-4645)
This is to warn of pods running above what they requested which puts them at the risk of being evicted in the case of cluster pressure, not only that but it also should signal a change in the behaviour of the pod and might require a revision of the requested resources.
> Pod exceeding cpu & memory requested alerts

- rhobs/alerting/data_plane/prometheus.mintmaker_controller_up_alerts.yaml
- rhobs/alerting/data_plane/prometheus.multi_platform_alerts.yaml
- test/promql/tests/data_plane/mintmaker_controller_up_test.yaml
- test/promql/tests/data_plane/multi_platform_alerts_test.yaml
Adding alerts rules for MintMaker and MPC konflux_up recordings
Adding unit tests for those alert rules
These are done using Prometheus yamls. This is part of an effort to  enhance Konflux observability, help in incident  response, and provide  a better user experience.
Signed-off-by: Mário Fernandes <mfoganho@redhat.com>
IMPORTANT: merge after https://github.com/redhat-appstudio/o11y/pull/552
> MPC and MintMaker alerts

- rhobs/alerting/data_plane/prometheus.project_controller_up_alerts.yaml
- test/promql/tests/data_plane/project_controller_up_test.yaml
The alert is firing every once in a while and till now was always resolving itself. Given this and the nature of the work done with this controller (very sporadic and not very time sensitive) we can make the alert less sensitive.
> fix(KFLUXVNGD-319): make project-controller alarm less sensitive

- config/exporters/monitoring/kanary/base/kanary-exporter-service.yaml
The reason behind this is to be able to distinguish between the dsexporter and the kanaryexporter using the job label in the metric.
> chore: rename kanary exporter service and deployment names

- exporters/kanaryexporter/kanaryexporter.go
This is due to the "instance" label being reserved for the IP:PORT of the endpoint the metric is coming from, which was leading our label "instance" to become "exported_instance". This could cause confusion mapping and connecting the metric labels with the code.
> chore: change kanary instance label to tested_cluster

- rhobs/alerting/data_plane/prometheus.pod_alerts.yaml
There is a huge amount of alerts reaching out to #konflux-misc-channel in relation to PodNotReady for MPC namespace, these are related with Provisioning/cleanup/update pods are not a real indicator that something is happening on MPC namespace (discussed with Infra Team).
We have decided to remove MPC namespace to reduce the noise, since the pods that we really want to monitor are already under konflux_up signal and there is an alert already for that.
@jdcasey @raks-tt
> feat(SPRE-1521): PodNotReady MPC namespace removal

- rhobs/alerting/data_plane/prometheus.kanary_alerts.yaml
This is due to the fact that validation of the alert seems to require a value > 0 for the "for" rule spec.
> fix(PVO11Y-4764): kanary alerts should fire after 1s

- dashboards/grafana-dashboard-kanary-signal.configmap.yaml
The dashboard was initially created on the grafana UI and the json file (with its uid) was used to push the dashboard using gitops under o11y/dashboards which was causing unexpected behavior, due to the duplication of the same uid.
The suspicion is that identical uids is causing grafana to have some form of "race condition".
> fix(PVO11Y-4804): Resolve Kanary Grafana dashboard UID conflict

- rhobs/alerting/data_plane/prometheus.kanary_alerts.yaml
- test/promql/tests/data_plane/kanary_test.yaml
What was done:
- A new alert for absence of kanary metrics from the exporter
- Refactor the tests of the alerts
- Modify the alerts to differentiate between the production and staging clusters
- SOP Reference to the kanary SLO alert added
> Kanary alerts rework

- rhobs/alerting/data_plane/prometheus.prometheus_alerts.yaml
- test/promql/tests/data_plane/prometheus_alerts_test.yaml
Alerts for instances when no Prometheus instance exists in a state of 'prometheus_ready=1' for each of the three Prometheus deployments.
> PVO11Y-4773 - Alerts for the 3 Prometheus instances

- rhobs/alerting/data_plane/prometheus.smee_up_alerts.yaml
- rhobs/recording/smee_availability_recording_rules.yaml
- test/promql/tests/data_plane/smee_up_test.yaml
This change adds a recording rule to capture the konflux_up metric for both smee server and client. It then uses that metric for an alerting rule.
The metric is based on a new liveness probe that triggers a live test for the smee client/server for verifying that smee is still serving properly.
See: https://github.com/konflux-ci/smee-sidecar
> chore(KFLUXVNGD-334): smee konflux_up metric and alerting rule

- rhobs/alerting/data_plane/prometheus.api_server_alerts.yaml
- rhobs/recording/api_server_availability_recording_rules.yaml
- test/promql/tests/data_plane/api_server_availability_test.yaml
- test/promql/tests/recording/api_server_availability_recording_rules_test.yaml
The recording rule had a threshold similar to the alert expression, and without a unit test it wasn't detected. This adds the test then fixes the rule.
> fix(SPRE-1542): Adding recording rule test and fix rule

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
- rhobs/alerting/data_plane/prometheus.kubearchive_availability.yaml
* Created basic SLO alerts based on the `konflux_up` metric, will refine in the future.
* I added a new row with KubeArchive's SLO in the dashboard, but the diff got all screwed up. I just copied directly from the Grafana export window.
> KuebArchive: add basic SLO alerts

- dashboards/grafana-dashboard-rhtap-slos.configmap.yaml
PR #652 accidentally changed the Konflux SLOs dashboard's name and uid which change the URL to the dashboard. Restore the original name and uid to restore the original URL to the dashboard.
> fix(PVO11Y-4840): Restore Konflux SLOs dashboard name and uid

- rhobs/alerting/data_plane/prometheus.pipeline_alerts.yaml
- test/promql/tests/data_plane/pipelines_up_test.yaml
Add a Prometheus alert rule for every Pipelines component which is
depended on by Konflux based on that component's konflux_up signal
Resolves: https://issues.redhat.com/browse/SRVKP-7880
Depends on https://github.com/redhat-appstudio/o11y/pull/638
> chore(SRVKP-7880): Add Pipelines SLO alerts for konflux_up signals

- rhobs/recording/api_server_availability_recording_rules.yaml
api_server konflux up alert is visibile on production but it is not on the observability exporter: https://grafana.app-sre.devshift.net/d/fdifr5mbapv5sb/availability-exporter-dashboard?orgId=1&from=now-5m&to=now&timezone=browser&var-Datasource=P22466E8E7855F1E0&var-service=api-server&var-check=$__all&var-cluster=$__all
We need to convert the error rate into:
konflux_up = 1 if the API server's 5-minute error rate is below 5%.
konflux_up = 0 if the API server's 5-minute error rate is 5% or above.
> fix(SPRE-1542) Observability dashboard fix

- rhobs/recording/api_server_availability_recording_rules.yaml
- test/promql/tests/recording/api_server_availability_recording_rules_test.yaml
Based on https://issues.redhat.com/browse/SPRE-1542 the konflux_up signal works correctly but for some reason was not getting displayed into the availability exporter dashboard.
We have converted the values into boolean and that should do the trick.
> fix(SPRE-1542) API Server code fix

- rhobs/alerting/data_plane/prometheus.kyverno_alerts.yaml
- test/promql/tests/data_plane/kyverno_test.yaml
Add Kyverno Controller Requeue Errors and Policy Failures Alerts.
This PR introduces two new Prometheus alerts to enhance our monitoring of Kyverno's operational health and policy enforcement:
* **Trigger:** Kyverno internal controllers are encountering errors, causing items to be re-queued for 3 consecutive minutes.
* **PromQL Concept:** This alert uses `increase(kyverno_controller_requeue_total[1m]) > 0` with a `for: 3m` clause.
* **Runbook (in progress):** Refer to the updated Kyverno Runbook for troubleshooting: [https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/kyverno/README.md](https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/kyverno/README.md)
* **Trigger:** Kyverno policies are failing or erroring out more than usual (specifically, more than 10 new …
> Added two new Prometheus alerts for kyverno

- rhobs/recording/mintmaker_service_quality_recording_rules.yaml
- test/promql/tests/recording/mintmaker_service_quality_recording_rules_test.yaml
This commit introduces two observatility metrics that will be used in MintMaker's dashboard, and their tests.
The two metrics are related to cluster memory:
- cluster memory requested percentage (as in requested/available)
- percentage of nodes in MemoryPressured state
This is because, if the cluster is experiencing high memory demand, it will probably have issues when processing the MintMaker pipelineruns, and the service might degrade.
> MintMaker cluster ram metrics

- dashboards/grafana-dashboard-konflux-ui-pods-availability.configmap.yaml
Add dashboard to display pods' availability of Konflux UI application.
[Dashboard](https://grafana.stage.devshift.net/goto/_hkr6qUHR?orgId=1) in grafana.
> feat(KFLUXUI-613): add dashboard for Konflux UI pods availability

- rhobs/alerting/data_plane/prometheus.kanary_alerts.yaml
- test/promql/tests/data_plane/kanary_test.yaml
This change is done to enable alerting for not just the container kanary signal (and error) but also for RPMs and any other types that would be supported down the road.
Assisted-by: Cursor
> chore(PVO11Y-4833): Enable Kanary alerts to include the type

- dashboards/grafana-dashboard-kanary-signal.configmap.yaml
- Added a new variable in the dashboard 'kanary_type'
- Only 1 type could be viewed at a time (this is to avoid complexities in the aggrigation process of same cluster names but with different signals according to the artifact type)
Issue: [PVO11Y-4834](https://issues.redhat.com/browse/PVO11Y-4834)
> feat: Enable kanary dashboard to filter by artifact type

- dashboards/grafana-dashboard-konflux-ui-endpoint-availability.configmap.yaml
Dashboard with the graph visualization for endpoint availability in the cluster where the application is running.
This dashboard aims to provide a simple and quick way for SREs realize if there is a problem in Konflux UI is not available in one of the clusters.
Jira KFLUXUI-605
[Dashboard](https://grafana.stage.devshift.net/goto/ans2hKwNR?orgId=1) in grafana.
> feat(KFLUXUI-605): add dashboard konflux ui endpoint availability

- dashboards/grafana-dashboard-konflux-ui-dex-availability.configmap.yaml
In this PR we're adding the `ConfigMap` to create the "Dex Availability" Dashboard for `konflux-ui`.
Fixes https://issues.redhat.com/browse/KFLUXUI-615
This is the [Dashboard](https://grafana.stage.devshift.net/goto/wf93AKQHR?orgId=1).
1. That's how the dashboard looks like (Last 24 hours - from the creation of this PR):
2. That's an example of a time in which the `stone-prod-p02` cluster had a down time:
☕
> [Konflux UI] Add dex availability dashboard

- dashboards/grafana-dashboard-konflux-ui-pod-restarts.configmap.yaml
Add visualization for konflux ui pod restarts
Link for the [dashboard](https://grafana.stage.devshift.net/goto/ZJ41ILlNR?orgId=1)
Jira KFLUXUI-604
> feat(KFLUXUI-604): Add konflux pod restart dashboard

- rhobs/alerting/data_plane/prometheus.kueue_alerts.yaml
- test/promql/tests/data_plane/kueue_alerts_test.yaml
Status 400 is returned when a malformed request is sent to the webhook. This can happen because of user configuration and because of that it's out of scope of this alert (which is about queuing).
> KFLUXINFRA-2089: Kueue ignore code 400 in webhook metric

- dashboards/grafana-dashboard-konflux-ui-pods-availability.configmap.yaml
Display in one single dashboard information about pod availability from Prod and Stage environment as well as both running pods through filters and add the restart counter for container images so users can debug in one single space.
Dashboard available [here](https://grafana.stage.devshift.net/goto/tTeIuPXNR?orgId=1)
Jira KFLUXUI-707
> refactor: add beter visualizations and filter

- rhobs/alerting/data_plane/prometheus.mintmaker_controller_up_alerts.yaml
- test/promql/tests/data_plane/mintmaker_controller_up_test.yaml
This commit changes the alert times from 5 to 15 minfor MintMaker availability, in order to make the alerts less flapping and more reliable.
> Increase alert time for MintMaker alerts

- dashboards/grafana-dashboard-konflux-integration-service-slo.configmap.yaml
One assessment panel & one violations panel added for
SLO 'Service response' times. Added a link to the Konflux
Namespace dashboard. Change name of dashboard to
Konflux - Integration Service SLO and remove 'availability'
label and put in 'SLO' label
> chore(stoneintg-1325): add latency service reponse SLO panels

- rhobs/alerting/data_plane/prometheus.backup_alerts.yaml
- test/promql/tests/data_plane/backup_failed_test.yaml
Include new backup alerts (severity might be updated later).
- Backup Not Running alert.
- Backup Partial Failure alert.
- Backup Long Running alert.
- Updated alert routing.
> New backup alerts

- dashboards/grafana-dashboard-internal-services-breakdown.configmap.yaml
- dashboards/grafana-dashboard-konflux-api-server-activity.configmap.yaml
- dashboards/grafana-dashboard-release-service.configmap.yaml
To continue with the SLO work implementation, we are now moving 2 dashboards from stage to production for release service
Dashboards in stage:
- https://grafana.stage.devshift.net/d/deyjgvpq0ta0wb/rugomez-internal-services-breakdown?var-interval=5m&orgId=1&from=now-3h&to=now&timezone=browser&var-pod=$__all&refresh=1m
- https://grafana.stage.devshift.net/d/deyjh44ia82dcf/rugomez-release-service-breakdown?var-interval=5m&orgId=1&from=now-3h&to=now&timezone=browser&var-cluster=$__all&var-tenant=$__all&refresh=1m
Also, I have just change one of the panels of api server:
from:
`avg by (source_cluster) (rate(process_cpu_seconds_total{job="apiserver", source_cluster=~"$cluster"}[5m]))`
to:
`sum by (source_cluster) (rate(process_cpu_seconds_total{job="apiserver", …
> feat(RELEASE-1632) Release service dashboard

- rhobs/alerting/data_plane/prometheus.mintmaker_controller_up_alerts.yaml
- test/promql/tests/data_plane/mintmaker_controller_up_test.yaml
This commit implements an alert in case the DUC creation is not taking place as expected.
DUCs are a custom resource in MintMaker that acts as triggers. If they are not created at the expected times, we should fire a warning.
Assisted by: Cursor
> MintMaker DUC alerting

- dashboards/grafana-dashboard-kanary-signal.configmap.yaml
---
Increase height of the top kanary panels
I want to be able to see the history trends for the kanary signals for all production clusters at the same time, but right now the panel is short enough that the data gets reduced to a single number if I select every prod cluster.
I didn't test that "15" was the right height. I just picked a number that was a little bit more than the current number to see how that fares.
> Increase height of the top kanary panels

- dashboards/grafana-dashboard-mintmaker.configmap.yaml
This commit adds a Grafana dashboard for MintMaker as a configmap.
You can check the manually-created version of the dashboard in [stage](https://grafana.stage.devshift.net/goto/cCkhxZqNg?orgId=1).
JIRA: CWFHEALTH-4180
> feat(CWFHEALTH-4180): Add MintMaker Grafana dashboard

- dashboards/grafana-dashboard-konflux-kubearchive-slo.configmap.yaml
Our SLO dashboard was using `konflux_up` without filtering it by cluster, leading to confusion. This PR solves it. Closes KAR-612.
---
---
Once your PR is ready please let us know in the [#forum-konflux-o11y](https://redhat.enterprise.slack.com/archives/C04FDFTF8EB) slack channel. Tag `@konflux-o11y-ic` for assistance.
> KubeArchive (KAR-612): fix konflux_up on SLO

- rhobs/alerting/data_plane/prometheus.integration_service_build_pipeline_to_snapshot_in_progress_alerts.yaml
- test/promql/tests/data_plane/integration_service_build_pipeline_to_snapshot_in_progress_test.yaml
The buildPLR to snapshot marked as in progress SLO for Integration Service is flapping on p02 and rh01, self resolves very quickly. Changing measurement time to 20 mins to prevent flapping.
https://issues.redhat.com/browse/STONEINTG-1369
---
---
---
Once your PR is ready please let us know in the [#forum-konflux-o11y](https://redhat.enterprise.slack.com/archives/C04FDFTF8EB) slack channel. Tag `@konflux-o11y-ic` for assistance.
> fix(stoneintg-1369): fix flapping alert by increasing measurement time
